### PR TITLE
fix: Consciencia negra day is not a national holiday

### PR DESCRIPTION
**Pull request by edniemeyer**
refs #

- [ ] Tests with a significant number of years to be tested for your calendar.
- [ ] Changelog amended with a mention describing your changes. **Note** *Please do NOT change the version number here. It's the project maintainers' duty.*

### CODE REVIEW

**Comment by brunobord** [comment]
Thanks for this patch, but I wish it was a bit more elaborated in order to fulfill its purposes. Could you please provide:

* a source that explains that this day is not a national holiday, since when, etc? I'm not sure that only switching from `True` to `False` would be enough if this day *was* a holiday and now isn't. There has been a few times in the past where we had to implement this kind of behaviour (a holiday that only appears since 2013, for example).
* at least one test case function where you see that this holiday doesn't appear at the national level, but would appear only for States that include it, and not the others (I'm a bit puzzled that the fact that you're switching it off in your patch didn't trigger a FAIL in tests... looks like our coverage is not as great as it should be)

**Comment by edniemeyer** [comment]
Sure! I would be happy to help! How can I add tests? Consciencia negra day is a holiday mandatory in some states, but not a national one. I've seen some of the states do have it setted correctly. Funny fact: carnival is said to be a non mandatory national holiday, even though it doesn't look like it in reality hahah. The BrazilBankCalendar class also I think should be the "official" Brazil class, which is usually what the companies follow over here, and what I used on my project.

Sources:

https://www.gov.br/pt-br/noticias/financas-impostos-e-gestao-publica/2020/01/portaria-divulga-feriados-e-pontos-facultativos-para-2020

https://g1.globo.com/economia/noticia/2020/01/01/veja-o-calendario-de-feriados-prolongados-e-de-pontos-facultativos-em-2020.ghtml

**Comment by brunobord** [comment]
ok. I see. As I want to have this bug fixed quickly, I'll take your branch over and try to make a bugfix release as soon as possible.
Stay tuned!

**Comment by brunobord** [comment]
(and I have time on my hands today, lucky you)

**Comment by brunobord** [comment]
Version 10.2.0 was released and published on PyPI, including bugfixes for Brazil calendars.
Have fun upgrading!

* https://github.com/peopledoc/workalendar/releases/tag/10.2.0
* https://pypi.org/project/workalendar/10.2.0/

**Comment by edniemeyer** [comment]
Great!! Thanks!!

**Comment by brunobord** [comment]
we aim to please :o)

**Pull request closed without merging**
