### PR TITLE
new feature: method to export any Calendar to .ical

### PR DESCRIPTION
**Pull request by joooeey**
Introducing a a feature originally discussed in #197

### Feature Description

This adds a method to the calendar class which allows users to export the calendar to the standard `.ical` format.

Usage:
```
>>> cal = Austria()
>>> cal.export_to_ical('austrian_calendar')  # -> austrian_calendar.ics
```
iCalendar is the standard for calendar sharing and hence `.ics` files can be imported into almost all Calendar apps on desktop computers, smartphones, and even dumbphones. For details see: [https://icalendar.org/](https://icalendar.org/)

### Release management

- Commit for the tag:
    - [ ] Edit version in setup.py
    - [ ] Add version in Changelog.md ; trim things
    - [ ] Push & wait for the tests to be green
    - [ ] tag me.
    - [ ] build sdist + wheel packages (``make package``)
- Back to dev commit:
    - [ ] Edit version in setup.py
    - [ ] Add the "master / nothing to see here" in Changelog.md
    - [ ] Push & wait for the tests to be green
- [ ] Merge --ff
- Github stuff
    - [ ] Push tag in Github
    - [ ] Edit release on Github using the changelog.
    - [ ] Delete branch
- [ ] upload release on PyPI using ``twine``
- [ ] (*optional*) Make feeback on the various PR or issues.

### CODE REVIEW

**Comment by joooeey** [comment]
Tests are failing due to a new dependency required for this feature: `import icalendar`. How to deal with this?

**Comment by joooeey** [comment]
> Tests are failing due to a new dependency required for this feature: `import icalendar`. How to deal with this?

It should not be a lot of effort to remove that dependency and hard-code the .ics output directly without using an outside library. Watch out for that commit in the next couple days..

**Comment by brunobord** [comment]
hello,

Looks like a good start. I'll try to have a look at it.
It might eventually lead to an optional requirement, but I'm going to need a bit of time to find an nice way to do it.

**Comment by joooeey** [comment]
I did remove the `icalendar` dependency. The code gets slightly shorter when directly coding the format required by the relevant standard [RFC 5545](https://tools.ietf.org/html/rfc5545). I also ran the file produced by `Germany().export_to_ical('test_germany')` through the linked [RFC 5545 Validator](https://icalendar.org/validator.html#results), with success.

**Comment by joooeey** [comment]
Hey Bruno!

I'm happy to work on this to make it good. This will be slow though, as I can't dedicate much time to this project. I was lazy about the changelog and docs (1 & 2)  because I first wanted to see if there was interest in adding this.

A couple technical points:

3 - I'm not very keen to work on this bug at all as I don't understand how US holidays work and what kind of holidays workalendar intends to include. So I'm very much hoping that someone else fixes this properly and I can just merge in that PR when I'm done with my changes so that my test runs clean.

4 - I don't like splitting up the function as I don't see why I should. What's the user story where somebody needs a different output than a file? The way `export_to_ical` is written like now, it doesn't just take a path but also other file-like objects, so it does accommodate users that don't want to write to disc. I think all I have to do is re-write the tests so they call the method with a file-like object that doesn't write to disc (some StringIO stuff if I recall correctly). Then I'd need to add a single test writing a single file just to check if the extension handling works the way it should. Sound good? If we go that way and remove the failed tests folder, we'll miss the failed test files for debugging if test failures crop up in the future. And they will crop up as plenty of general bugs in the workalendar module will lead to RFC 5545 violations (case in point: Cesar Chavez Day). I don't think this is a big deal as any developer can write those files themselves, it does sacrifice some debugging efficiency though. I originally put it that way because on my legacy laptop, including that test with writing to HDD didn't increase overall test time significantly. Something with avoiding premature optimization. But I guess there can always be devs with worse hardware.

5 - yup I overlooked that. Should do some input checking.

6 - A little background on why it's redundant: I wrote the implementation with the icalendar module and the tests first, then discovered that icalendar is not as helpful as I had hoped, and then wrote the current code. I was also hoping that icalendar would help with validation but I checked and the module appears to do close to now validity checking. It definitely lets through `VEVENT` entries without `UID` although that field is required by the RFC 5545 spec. That's why I would like to leave icalendar out. Checking for all requirements of the standard would quickly blow this project out of proportion. I searched for open-source RFC 5545 validation and couldn't find anything that works and can easily be incorporated into workalendar. The most useful stuff I found is [The iCalendar Validotar](https://icalendar.org/validator.html) which is a webform. I've run a few outputs of my code through it just to be sure they are valid. There's also [http://icalvalid.cloudapp.net/](http://icalvalid.cloudapp.net/) which I can't reach. I'm really not sure what amount of testing makes sense. The current tests basically just make sure that all fields are spelled correctly but only checking for New Year's under the assumption that the rest will be fine. Then there's a test that the UID fields are unique within the calendar. I guess it's not a crazy amount of effort to check if all fields are spelled correctly. Perhaps one can check the file against a regex. Than on the other hand, full test coverage of RFC 5545 just seems way too much effort and worthy of its own Python module. I would very much appreciate an idea on how to incorporate an outside RFC 5545 validator in the testing of the proposed feature.

I'll get to all this in the next couple days.

**Comment by joooeey** [comment]
I looked into the icalendar module again and noticed that they do plenty of validity checking when parsing files but none when writing files. Hence I suggest we do include the `import icalendar` and do everything with the icalendar module as in my first commit. Then for the tests we'd just see if parsing the file logs any errors (icalendar only logs and doesn't raise when checking Event validity). (We can keep the file in memory, no need to write to disc.) Then I would keep a test to check if UIDs within one calendar are unique.

I'll definitely need your help with adding the dependency to the icalendar module to the project. I have no idea how to do that.

**Comment by brunobord** [comment]
> I'll definitely need your help with adding the dependency to the icalendar module to the project. I have no idea how to do that.

the requirements are simply listed in this list: https://github.com/peopledoc/workalendar/blob/master/setup.py#L21-L30
Adding a dependency is as simple as adding it to this list.

> This will be slow though, as I can't dedicate much time to this project.

Yeah, a bit of the same here: summertime is not the best time of the year to work on a side project, with vacations, and all... but don't despair, this contribution won't be forgotten.

> The way export_to_ical is written like now, it doesn't just take a path but also other file-like objects

mmmm... not really. it takes a string as a path that you may open for write.

see: https://github.com/peopledoc/workalendar/pull/527/files#diff-c8773c3a29eba8fa93fa4b7a0197b878R848-R852
(and to be honest, I don't see the point of providing a mechanism to add the extension if required, if I want to create a `/tmp/foobar.txt` file, I couldn't, because you would transform it into a `/tmp/foobar.txt.ics` file).

> I think all I have to do is re-write the tests so they call the method with a file-like object that doesn't write to disc

Possibly, yes. But my point was to separate the *content* generation from the *file* generation. I think it's easier to separate internal computations from the Input/Output. Maybe it's just me, but I'm used to the fact that a program can write an export to the standard output and then *as an option*, being able to write to disk. This is more flexible if you want to `grep` your content or manipulate though a pipeline. And the output of your function could be manipulated without having to extract it from a file-like object, simply as a string. But yes, it's probably a matter of taste.

We'll see where this is going (slowly, but I have hope)

**Pull request closed without merging**
