### PR TITLE
Add All Souls Day to Lithuania

### PR DESCRIPTION
**Pull request by brunobord**
superseeds, and thus closes #512

- [x] Tests with a significant number of years to be tested for your calendar.
- [x] Changelog amended with a mention describing your changes. **Note** *Please do NOT change the version number here. It's the project maintainers' duty.*

### CODE REVIEW

**Comment by brunobord** [comment]
@norkunas even if you're not into Python, could you please have a look at this? I hope it's self-explanatory. If you have any remarks, please do ;o)

**Comment by norkunas** [comment]
Looks good 👍

**Comment by norkunas** [comment]
Thank you :)

**Comment by brunobord** [comment]
I'll publish a release in a few moments.

**Pull request merged**
