### PR TITLE
Add All Souls Day to Lithuania

### PR DESCRIPTION
**Pull request by norkunas**
refs #

Sorry, I'm not a python guy, so just adding this via GH UI :)

### CODE REVIEW

**Comment by brunobord** [comment]
hey! don't worry, using Github UI is not a crime ;o)

Although you miss a few steps before it being perfectly valid (add tests, changelog, etc). If you're definitely not a Python guy, I could take over your PR (with all credits due)...
Although, if it's possible, could you give me a link/hint on how/why this day has been added to the Lithuania calendar? Is it just for this year, or starting of this year, or since forever?

**Comment by brunobord** [comment]
mmmm as I can see it was decided in 2019: https://www.lrt.lt/en/news-in-english/19/1089741/lithuania-makes-all-souls-day-a-public-holiday

so the question becomes: did November 2nd 2019 a holiday, or will it start in 2020?

**Comment by norkunas** [comment]
It will start in 2020 :)

**Comment by norkunas** [comment]
> hey! don't worry, using Github UI is not a crime ;o)
> 
> Although you miss a few steps before it being perfectly valid (add tests, changelog, etc). If you're definitely not a Python guy, I could take over your PR (with all credits due)...
> Although, if it's possible, could you give me a link/hint on how/why this day has been added to the Lithuania calendar? Is it just for this year, or starting of this year, or since forever?

I'm fine if you will take it over ;)

**Comment by brunobord** [comment]
great! Will work on it ASAP!

**Comment by brunobord** [comment]
Version 10.1.0 with Lithuania's fix is now available:

* https://github.com/peopledoc/workalendar/releases/tag/10.1.0
* https://pypi.org/project/workalendar/10.1.0/

Happy upgrading!

**Pull request closed without merging**
