### PR TITLE
Add Cayman Islands.

### LINKED ISSUE #328: America:  Cayman Island calendar
Add support for Cayman Island calendar

As many banks and institutions are working with Cayman Islands funds or banks I believe this will be very useful and help to rocket this library at the corporate level.

### PR DESCRIPTION
**Pull request by Natim**
Fixes #328

- [x] Tests with a significant number of years to be tested for your calendar.
- [x] Docstrings for the Calendar class and specific methods.
- [x] Use the ``workalendar.registry.iso_register`` decorator to register your new calendar using ISO codes (optional).
- [x] Calendar country / label added to the README.rst file,
- [x] Changelog amended with a mention like: "Added ``<country>`` by ``@pseudo`` (#)"

### CODE REVIEW

**Comment by brunobord** [comment]
Queen's Birthday can be computed: https://www.officeholidays.com/countries/cayman_islands/queens_birthday.php and it's definitely not a fixed holiday.

> n the Cayman Islands, this holiday is usually celebrated on the Monday after the Saturday in June that is designated as the official holiday observance in the United Kingdom. Generally it is the second Saturday in June.

The cool thing is that you already have tests so reimplementing it will be piece of cake **and** it shouldn't break anything.

```python
sat = self.get_nth_weekday_in_month(year, 6, SAT, 2)
holiday = sat + timesdelta(days=2)
```

**Comment by Natim** [comment]
Actually, this is what I had in https://github.com/peopledoc/workalendar/pull/329/commits/4454e3a22b10d159a7ee23c8d89c6a63702048ea#diff-12dbdffc67cb7f43f25ed946eb64ea30L6 and it doesn't work for 2017 and 2020 because Caymand Islands change the rule sometimes.

**Comment by Natim** [comment]
Can we say that if the second saturday is after the 10th, then it gets to the 3rd monday?

**Comment by Natim** [comment]
I guess I can count you in the group of people that rewrite history... :smile: 

- Git history matters: https://tech.people-doc.com/git-history-matters.html https://tech.people-doc.com/git-history-matters-example.html

**Pull request merged**
