### PR TITLE
Israel - Fixed incorrect Purim/Shushan Purim dates in jewish leap years

### PR DESCRIPTION
**Pull request by orzarchi**
The holiday of Purim was incorrectly showing as happening twice in 2019 (2019-02-19 and 2019-03-21), due to 2019 being a jewish leap year.
Also fixed the alternative holiday Shushan Purim **only** appearing in leap years, where in reality it happens every year the day after regular Purim. 

- [X] Tests with a significant number of years to be tested for your calendar.
- [X] Changelog amended with a mention describing your changes.

### CODE REVIEW

**Comment by brunobord** [comment]
I'm going to trust you on this one, I don't have enough knowledge on the Hebraic calendar. Will try to make a hotfix release as soon as I can.

**Comment by brunobord** [comment]
(tagged, released](https://github.com/peopledoc/workalendar/releases/tag/5.0.1) and [available on PyPI](https://pypi.org/project/workalendar/5.0.1/).
Have a nice day.

**Comment by orzarchi** [comment]
@brunobord 
The plot thickens.
After some research it seems like only part of my fix was correct.
I was basing my tests on the official [israeli holiday calendar](https://info.goisrael.com/en/purim-286971)
But it's misleading. (It combines Purim and Shushan Purim, that happen day after day)
The previous shushan purim calculation was correct according to these sources:
[timeanddate.com](https://www.timeanddate.com/holidays/israel/2020)
[wikipedia](https://en.wikipedia.org/wiki/Purim)
Should I create a new PR?
Sorry for the trouble.

**Comment by brunobord** [comment]
ah. yes, you may create a new pull-request ; I'll add a warning on the release and changelog after that.

And don't worry about the trouble: since I started this project, I've seen ups and downs and way too many bizarre things to be disappointed.

Thank you for your contribution!

**Pull request merged**
