### PR TITLE
add europe day for Luxembourg

### PR DESCRIPTION
**Pull request by sim0nx**
Since this year there is a new national holiday in Luxembourg "Europe Day".

- [x] Tests with a significant number of years to be tested for your calendar.
- [x] Changelog amended with a mention describing your changes.

### CODE REVIEW

**Comment by brunobord** [comment]
Hi! Thanks a lot for this contribution, much appreciated!

However, if it's "since this year", I guess that this pull-request is wrong.

You may want to test that, prior to 2019, this Europe Day isn't a holiday, and in 2019 and beyond, this day was integrated into the holidays.
You may want to override the ``get_fixed_holidays`` method and test the value of the parameter "year" to correctly implement this.

**Comment by sim0nx** [comment]
> Hi! Thanks a lot for this contribution, much appreciated!
> 
> However, if it's "since this year", I guess that this pull-request is wrong.
> 
> You may want to test that, prior to 2019, this Europe Day isn't a holiday, and in 2019 and beyond, this day was integrated into the holidays.
> You may want to override the `get_fixed_holidays` method and test the value of the parameter "year" to correctly implement this.

Good point, oops! :-)
I fixed that.

**Comment by brunobord** [comment]
Looks excellent! I'll try to merge this and make a bugfix release as soon as I can, stay tuned!

**Comment by sim0nx** [comment]
> Looks excellent! I'll try to merge this and make a bugfix release as soon as I can, stay tuned!

Great! Appreciate it!

**Comment by brunobord** [comment]
version 5.1.1 released on PyPI. Enjoy! https://pypi.org/project/workalendar/5.1.1/

**Comment by sim0nx** [comment]
Thanks! :-)

**Pull request merged**
