### PR TITLE
Separate tests from the source code and use src/

### PR DESCRIPTION
**Pull request by eumiro**
Move all source code to `src/workalendar` and move tests to `tests`. Fix all imports in tests. Fix paths in `setup.cfg` and `tox.ini`.

### CODE REVIEW

**Comment by brunobord** [comment]
Could you please explain the rationale behind this? Historically, the tests were included in the package because I've been told it's a good practice when you want to package for Debian (even if I'm not sure if anybody has ever tried to package workalendar for Debian)

**Comment by brunobord** [comment]
For the record: https://github.com/peopledoc/workalendar/issues/144

**Comment by brunobord** [comment]
for the move to the `src` directory, I find this practice unpractical. (personal opinion, not evidence-based)

**Comment by eumiro** [comment]
I have learned it that way and saw enough recommendations to do it that way. For me this was a good occasion to practice the migration and I did not see the change in #144, so please feel free to close this PR.

**Comment by brunobord** [comment]
I'm going to close this PR, but I hope it won't stop you to contribute!
Have a nice day.

**Pull request closed without merging**
