### PR TITLE
Update Cuiaba-Brazil holidays

### PR DESCRIPTION
**Pull request by leogregianin**
refs #

For information, read and make sure you're okay with the [Contributing guidelines](https://peopledoc.github.io/workalendar/contributing.html#adding-new-calendars).

- [x] Tests with a significant number of years to be tested for your calendar.
- [x] Docstrings for the Calendar class and specific methods.
- [x] Use the ``workalendar.registry_tools.iso_register`` decorator to register your new calendar using ISO codes (optional).
- [x] Calendar country / label added to the README.md file.
- [x] Changelog amended with a mention like: "Added ``<country>`` by ``@pseudo`` (#)". **Note** *Please do NOT change the version number here. It's the project maintainers' duty.*

- [x] Tests with a significant number of years to be tested for your calendar.
- [x] Changelog amended with a mention describing your changes. **Note** *Please do NOT change the version number here. It's the project maintainers' duty.*

### CODE REVIEW

**Comment by brunobord** [comment]
Looks like a great contibution, here. Could you please at least provide a rationale about this change? Why would this calendar be changed? Is it a change that only occurs since 2021?

**Comment by leogregianin** [comment]
Corpus Christi and Good Friday are religious dates and are instituted each year by city. And it's a local tradition of several years, always holidays in several cities like Sao Paulo. In Cuiaba, Brazil see the references [1](https://pt.wikipedia.org/wiki/Feriados_no_Brasil), [2](https://www.feriados.com.br/feriados-cuiaba-mt.php), [3](https://www.gazetadigital.com.br/editorias/cidades/cuiab-ter-13-feriados-e-6-pontos-facultativos-em-2021/640065)

**Comment by brunobord** [comment]
thank you very much, and sorry for the delay ; I'll try to merge and make a bugfix release today.

**Comment by brunobord** [comment]
version 15.2.0 was released and publish on PyPI, happy upgrading!

* https://pypi.org/project/workalendar/15.2.0/
* https://github.com/peopledoc/workalendar/releases/tag/15.2.0

**Pull request closed without merging**
